services:
  postgres:
    image: postgres:12.21-bookworm
    volumes:
      - type: bind
        source: ./dbData/
        target: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin